version: "3"
services:
  superset:
    image: amancevice/superset
    container_name: superset
    privileged: true
    user: root
    environment:
      - SUPERSET_ADMIN_USERNAME=admin
      - SUPERSET_ADMIN_PASSWORD=admin
      - SUPERSET_LOAD_EXAMPLES=yes
    volumes:
      - ./superset:/home/superset
      - ./data:/var/lib/superset
      - ./superset/conf:/etc/superset
      - ./superset_config.py:/etc/superset/superset_config.py
    ports:
      # 这个和YarnRmWeb的 8088冲突了
      - 18088:8088

