
scrape_configs:
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['localhost:8428']

  - job_name: 'kafka'
    static_configs:
      - targets: ['192.168.51.124:9308']
        labels:
          instance: 'kafka@192.168.51.124:9092'
