version: "3.8"

services:
  victoriametrics_vm_8428:
    image: victoriametrics/victoria-metrics
    container_name: victoriametrics_vm_8428
    ports:
      - "8428:8428"
    volumes:
      - ./vm-data:/victoria-metrics-data
      - ./victoriametrics:/victoriametrics
      - ./prometheus.yml:/etc/prometheus.yml
    command:
      - '-promscrape.config=/etc/prometheus.yml'
      - '-retentionPeriod=30d'

  grafana_vm_3000:
    image: grafana/grafana:9.1.5
    container_name: grafana_vm_3000
    ports:
      - "3000:3000"

  node_exporter_vm_9100:
    image: quay.io/prometheus/node-exporter:v1.3.1
    container_name: node_exporter_vm_9100
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  kafka_exporter_vm_9308:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka_exporter_vm_9308
    ports:
      - "9308:9308"
    command:
      - '--kafka.server=${KAFKA_AD_IP}:9092'

  jmx_exporter_vm_9099:
    image: bitnami/jmx-exporter:0.16.1
    container_name: jmx_exporter_vm_9099
    ports:
      - "9099:9099"
    volumes:
      - ./jmx_config.yml:/etc/jmx_config.yml
    command:
      - '9099'
      - '/etc/jmx_config.yml'
