
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['localhost:8428']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka_exporter_vm:9308']
        labels:
          instance: 'kafka@192.168.51.102:9092'

  - job_name: 'node_expoerter'
    static_configs:
      - targets: ['node_exporter_vm_9100:9100']
        labels:
          host: 'node_exporter_vm_9100'
          ipAddress: '192.168.51.102'

  - job_name: 'kafka_jmx'
    static_configs:
      - targets: ['jmx_exporter_vm_9099:9099']
        labels:
          instance: 'kafka@192.168.51.102:9092'

