global:
  resolve_timeout: 5m
  smtp_smarthost:   #带端口
  smtp_from:
  smtp_auth_username:
  smtp_auth_password:

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'mememe'
receivers:
  - name: 'mememe'
    #webhook_configs:
    #- url: 'http://127.0.0.1:5001/'
    email_configs:
      - to: 'xxx@xxx.com'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']