version: "3"
services:
  jobmanager:
    image: ${FLINK_IMAGE:-flink:1.9.1-scala_2.11}
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    ports:
      - "8081:8081"
    volumes:
      - /opt/flink/log
    networks:
      - flinknet
  taskmanager:
    image: ${FLINK_IMAGE:-flink:1.9.1-scala_2.11}
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: ${TM_SLOTS_NUM:-4}
    volumes:
      - /opt/flink/log
    networks:
      - flinknet
networks:
  flinknet:
